import type { Metadata } from 'next';
import { Fira_Mono } from 'next/font/google';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import './globals.css';

const firaMono = Fira_Mono({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={firaMono.className}>
        <MantineProvider>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
